name: docker-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

      # https://github.community/t/add-short-sha-to-github-context/16418/11
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            dijksterhuis/tensorflow-1.15.5-pub-key-update:latest
            dijksterhuis/tensorflow-1.15.5-pub-key-update:${{ steps.slug.outputs.sha8 }}
          no-cache: true
          push: true
          pull: true
          file: ./Dockerfile
